<a href="https://colab.research.google.com/github/Sarth-k/Data-Analysis-using-ANN/blob/main/American_Express_Data_Analysis_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
dataset = pd.read_excel("American Express Data.xlsx")
dataset.head()

Credit Score  Geography  Gender  Age  Customer Since  Current Account  \
0           553      Delhi  Female   45               4            0.000   
1           447  Bengaluru    Male   31               7            0.000   
2           501      Delhi  Female   32               2            0.000   
3           428      Delhi    Male   51               3            0.000   
4           492      Delhi  Female   57               6      1912681.501   

   Num of products  UPI Enabled  Estimated Yearly Income  Closed  
0                4            1                   274150       0  
1                4            1                   519360       0  
2                4            1                   545501       0  
3                4            1                    86868       0  
4                2            1                   518680       0

In [ ]:
dataset.isnull().sum()

Credit Score               0
Geography                  0
Gender                     0
Age                        0
Customer Since             0
Current Account            0
Num of products            0
UPI Enabled                0
Estimated Yearly Income    0
Closed                     0
dtype: int64

In [ ]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
x

array([[553, 'Delhi', 'Female', ..., 4, 1, 274150],
       [447, 'Bengaluru', 'Male', ..., 4, 1, 519360],
       [501, 'Delhi', 'Female', ..., 4, 1, 545501],
       ...,
       [627, 'Mumbai', 'Female', ..., 4, 0, 494067],
       [600, 'Bengaluru', 'Female', ..., 2, 1, 109375],
       [553, 'Delhi', 'Male', ..., 4, 1, 180031]], dtype=object)

In [ ]:
y

array([0, 0, 0, ..., 0, 1, 0])

#Encoding categorical data

Gender column: label encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
lable_encoding = LabelEncoder()
x[:,2]=lable_encoding.fit_transform(x[:,2])

In [ ]:
x

array([[553, 'Delhi', 0, ..., 4, 1, 274150],
       [447, 'Bengaluru', 1, ..., 4, 1, 519360],
       [501, 'Delhi', 0, ..., 4, 1, 545501],
       ...,
       [627, 'Mumbai', 0, ..., 4, 0, 494067],
       [600, 'Bengaluru', 0, ..., 2, 1, 109375],
       [553, 'Delhi', 1, ..., 4, 1, 180031]], dtype=object)

Geography column One hot encoding

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
# x=np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


In [ ]:
x.shape

(9927, 11)

In [ ]:
print(y)

[0 0 0 ... 0 1 0]


# Spliting Dataset into traing and test dataset

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test  = train_test_split(x,y,test_size=0.2, random_state=42)


#Feature Selection

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train= sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
x_train

array([[-0.9933479 , -0.58505734,  1.73979202, ..., -0.95896254,
         0.64518632,  0.75774259],
       [ 1.00669664, -0.58505734, -0.57478135, ...,  0.89138894,
         0.64518632, -1.72124988],
       [ 1.00669664, -0.58505734, -0.57478135, ..., -0.95896254,
         0.64518632,  0.45400561],
       ...,
       [-0.9933479 ,  1.70923418, -0.57478135, ...,  0.89138894,
         0.64518632, -1.15372847],
       [ 1.00669664, -0.58505734, -0.57478135, ...,  0.89138894,
         0.64518632, -1.26520339],
       [ 1.00669664, -0.58505734, -0.57478135, ...,  0.89138894,
        -1.54993988, -0.65598438]])

#ANN

Initialization

In [ ]:
ann=tf.keras.models.Sequential()


Adding input layer & first hidden layer


In [ ]:
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))


Adding 2nd hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

Adding output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#ANN Training

ANN Compile

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Training of training dataset

In [ ]:
ann.fit(x_train, y_train, batch_size=32, epochs=120)

Epoch 1/120
249/249 [==============================] - 2s 3ms/step - loss: 0.6054 - accuracy: 0.7000
Epoch 2/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4838 - accuracy: 0.7976
Epoch 3/120
249/249 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7976
Epoch 4/120
249/249 [==============================] - 1s 5ms/step - loss: 0.4459 - accuracy: 0.7978
Epoch 5/120
249/249 [==============================] - 1s 5ms/step - loss: 0.4376 - accuracy: 0.7986
Epoch 6/120
249/249 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.7998
Epoch 7/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4265 - accuracy: 0.8023
Epoch 8/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4204 - accuracy: 0.8058
Epoch 9/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4130 - accuracy: 0.8093
Epoch 10/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4059 - accura

#Prediction

In [ ]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]]))> 0.5)

1/1 [==============================] - 0s 193ms/step
[[False]]


Prediction on test set

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


63/63 [==============================] - 0s 4ms/step
[[0 0]
 [0 0]
 [1 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[1495   70]
 [ 234  187]]


0.8469284994964753